spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orla_db
    username: joao
    password: joao123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
